rm -r histos/latest_production/mergedYearsSelection
mkdir histos/latest_production/mergedYearsSelection

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_DY_201620172018.root histos/latest_production/WPiGammaHistos_DY_2016.root histos/latest_production/WPiGammaHistos_DY_2017.root histos/latest_production/WPiGammaHistos_DY_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_GammaJets_201620172018.root histos/latest_production/WPiGammaHistos_GammaJets_2016.root histos/latest_production/WPiGammaHistos_GammaJets_2017.root histos/latest_production/WPiGammaHistos_GammaJets_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_QCD_201620172018.root histos/latest_production/WPiGammaHistos_QCD_2016.root histos/latest_production/WPiGammaHistos_QCD_2017.root histos/latest_production/WPiGammaHistos_QCD_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_STtW_201620172018.root histos/latest_production/WPiGammaHistos_STtW_2016.root histos/latest_production/WPiGammaHistos_STtW_2017.root histos/latest_production/WPiGammaHistos_STtW_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_TTGJets_201620172018.root histos/latest_production/WPiGammaHistos_TTGJets_2016.root histos/latest_production/WPiGammaHistos_TTGJets_2017.root histos/latest_production/WPiGammaHistos_TTGJets_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_WGToLNuG_201620172018.root histos/latest_production/WPiGammaHistos_WGToLNuG_2016.root histos/latest_production/WPiGammaHistos_WGToLNuG_2017.root histos/latest_production/WPiGammaHistos_WGToLNuG_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_WJetsToLNu_201620172018.root histos/latest_production/WPiGammaHistos_WJetsToLNu_2016.root histos/latest_production/WPiGammaHistos_WJetsToLNu_2017.root histos/latest_production/WPiGammaHistos_WJetsToLNu_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_WW_201620172018.root histos/latest_production/WPiGammaHistos_WW_2016.root histos/latest_production/WPiGammaHistos_WW_2017.root histos/latest_production/WPiGammaHistos_WW_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_WZ_201620172018.root histos/latest_production/WPiGammaHistos_WZ_2016.root histos/latest_production/WPiGammaHistos_WZ_2017.root histos/latest_production/WPiGammaHistos_WZ_2018.root 

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ZGTo2LG_201620172018.root histos/latest_production/WPiGammaHistos_ZGTo2LG_2016.root histos/latest_production/WPiGammaHistos_ZGTo2LG_2017.root histos/latest_production/WPiGammaHistos_ZGTo2LG_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ttbar_201620172018.root histos/latest_production/WPiGammaHistos_ttbar_2016.root histos/latest_production/WPiGammaHistos_ttbar_2017.root histos/latest_production/WPiGammaHistos_ttbar_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ttbarWQQ_201620172018.root histos/latest_production/WPiGammaHistos_ttbarWQQ_2016.root histos/latest_production/WPiGammaHistos_ttbarWQQ_2017.root histos/latest_production/WPiGammaHistos_ttbarWQQ_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ttbarWlnu_201620172018.root histos/latest_production/WPiGammaHistos_ttbarWlnu_2016.root histos/latest_production/WPiGammaHistos_ttbarWlnu_2017.root histos/latest_production/WPiGammaHistos_ttbarWlnu_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ttbarZQQ_201620172018.root histos/latest_production/WPiGammaHistos_ttbarZQQ_2016.root histos/latest_production/WPiGammaHistos_ttbarZQQ_2017.root histos/latest_production/WPiGammaHistos_ttbarZQQ_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ttbarZlnu_201620172018.root histos/latest_production/WPiGammaHistos_ttbarZlnu_2016.root histos/latest_production/WPiGammaHistos_ttbarZlnu_2017.root histos/latest_production/WPiGammaHistos_ttbarZlnu_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_ttbarlnu_201620172018.root histos/latest_production/WPiGammaHistos_ttbarlnu_2016.root histos/latest_production/WPiGammaHistos_ttbarlnu_2017.root histos/latest_production/WPiGammaHistos_ttbarlnu_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_Signal_201620172018.root histos/latest_production/WPiGammaHistos_Signal_2016.root histos/latest_production/WPiGammaHistos_Signal_2017.root histos/latest_production/WPiGammaHistos_Signal_2018.root

hadd histos/latest_production/mergedYearsSelection/WPiGammaHistos_Data_201620172018.root histos/latest_production/WPiGammaHistos_Data_2016.root histos/latest_production/WPiGammaHistos_Data_2017.root histos/latest_production/WPiGammaHistos_Data_2018.root
