
mkdir histos
mkdir latest_production

python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_DY10to50_2016.root histos/latest_production/WPigammaHistos_DY10to50_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_DY50_2016.root histos/latest_production/WPigammaHistos_DY50_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_GammaJets20to40_2016.root histos/latest_production/WPigammaHistos_GammaJets20to40_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_GammaJets20toInf_2016.root histos/latest_production/WPigammaHistos_GammaJets20toInf_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_GammaJets40toInf_2016.root histos/latest_production/WPigammaHistos_GammaJets40toInf_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDDoubleEMEnriched30to40_2016.root histos/latest_production/WPigammaHistos_QCDDoubleEMEnriched30to40_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDDoubleEMEnriched30toInf_2016.root histos/latest_production/WPigammaHistos_QCDDoubleEMEnriched30toInf_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDDoubleEMEnriched40toInf_2016.root histos/latest_production/WPigammaHistos_QCDDoubleEMEnriched40toInf_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT100to200_2016.root histos/latest_production/WPigammaHistos_QCDHT100to200_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT200to300_2016.root histos/latest_production/WPigammaHistos_QCDHT200to300_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT300to500_2016.root histos/latest_production/WPigammaHistos_QCDHT300to500_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT500to700_2016.root histos/latest_production/WPigammaHistos_QCDHT500to700_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT700to1000_2016.root histos/latest_production/WPigammaHistos_QCDHT700to1000_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT1000to1500_2016.root histos/latest_production/WPigammaHistos_QCDHT1000to1500_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT1500to2000_2016.root histos/latest_production/WPigammaHistos_QCDHT1500to2000_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT2000toInf_2016.root histos/latest_production/WPigammaHistos_QCDHT2000toInf_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_SingleAntiToptW_2016.root histos/latest_production/WPigammaHistos_SingleAntiToptW_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_SingleToptW_2016.root histos/latest_production/WPigammaHistos_SingleToptW_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_TTGJets_2016.root histos/latest_production/WPigammaHistos_TTGJets_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WGToLNuG_2016.root histos/latest_production/WPigammaHistos_WGToLNuG_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WJetsToLNu_2016.root histos/latest_production/WPigammaHistos_WJetsToLNu_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WW_2016.root histos/latest_production/WPigammaHistos_WW_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WZ_2016.root histos/latest_production/WPigammaHistos_WZ_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ZGTo2LG_2016.root histos/latest_production/WPigammaHistos_ZGTo2LG_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarWQQ_2016.root histos/latest_production/WPigammaHistos_ttbarWQQ_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarWlnu_2016.root histos/latest_production/WPigammaHistos_ttbarWlnu_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarZQQ_2016.root histos/latest_production/WPigammaHistos_ttbarZQQ_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarZlnu_2016.root histos/latest_production/WPigammaHistos_ttbarZlnu_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbar_2016.root histos/latest_production/WPigammaHistos_ttbar_2016.root
python generate_histos.py presel 0 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarlnu_2016.root histos/latest_production/WPigammaHistos_ttbarlnu_2016.root

hadd histos/latest_production/WPigammaHistos_QCD_2016.root histos/latest_production/WPigammaHistos_QCDHT*_2016.root
rm histos/latest_production/WPigammaHistos_QCDHT*_2016.root
