mkdir histos
mkdir histos/latest_production

rm histos/latest_production/*2017*.root

python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_DY10to50_2017.root histos/latest_production/WPiGammaHistos_DY10to50_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_DY50_2017.root histos/latest_production/WPiGammaHistos_DY50_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_GammaJets20to40_2017.root histos/latest_production/WPiGammaHistos_GammaJets20to40_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_GammaJets20toInf_2017.root histos/latest_production/WPiGammaHistos_GammaJets20toInf_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_GammaJets40toInf_2017.root histos/latest_production/WPiGammaHistos_GammaJets40toInf_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDDoubleEMEnriched30to40_2017.root histos/latest_production/WPiGammaHistos_QCDDoubleEMEnriched30to40_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDDoubleEMEnriched30toInf_2017.root histos/latest_production/WPiGammaHistos_QCDDoubleEMEnriched30toInf_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDDoubleEMEnriched40toInf_2017.root histos/latest_production/WPiGammaHistos_QCDDoubleEMEnriched40toInf_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT100to200_2017.root histos/latest_production/WPiGammaHistos_QCDHT100to200_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT200to300_2017.root histos/latest_production/WPiGammaHistos_QCDHT200to300_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT300to500_2017.root histos/latest_production/WPiGammaHistos_QCDHT300to500_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT500to700_2017.root histos/latest_production/WPiGammaHistos_QCDHT500to700_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT700to1000_2017.root histos/latest_production/WPiGammaHistos_QCDHT700to1000_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT1000to1500_2017.root histos/latest_production/WPiGammaHistos_QCDHT1000to1500_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT1500to2000_2017.root histos/latest_production/WPiGammaHistos_QCDHT1500to2000_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_QCDHT2000toInf_2017.root histos/latest_production/WPiGammaHistos_QCDHT2000toInf_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_SingleAntiToptW_2017.root histos/latest_production/WPiGammaHistos_SingleAntiToptW_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_SingleToptW_2017.root histos/latest_production/WPiGammaHistos_SingleToptW_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_TTGJets_2017.root histos/latest_production/WPiGammaHistos_TTGJets_2017.root
# python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WGToLNuG_2017.root histos/latest_production/WPiGammaHistos_WGToLNuG_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WGToLNuG01J_2017.root histos/latest_production/WPiGammaHistos_WGToLNuG_2017.root
# python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WJetsToLNu_2017.root histos/latest_production/WPiGammaHistos_WJetsToLNu_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WJetsToLNu0J_2017.root histos/latest_production/WPiGammaHistos_WJetsToLNu0J_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WJetsToLNu1J_2017.root histos/latest_production/WPiGammaHistos_WJetsToLNu1J_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WJetsToLNu2J_2017.root histos/latest_production/WPiGammaHistos_WJetsToLNu2J_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WW_2017.root histos/latest_production/WPiGammaHistos_WW_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_WZ_2017.root histos/latest_production/WPiGammaHistos_WZ_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ZGTo2LG_2017.root histos/latest_production/WPiGammaHistos_ZGTo2LG_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarWQQ_2017.root histos/latest_production/WPiGammaHistos_ttbarWQQ_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarWlnu_2017.root histos/latest_production/WPiGammaHistos_ttbarWlnu_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarZQQ_2017.root histos/latest_production/WPiGammaHistos_ttbarZQQ_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarZlnu_2017.root histos/latest_production/WPiGammaHistos_ttbarZlnu_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarlnu_2017.root histos/latest_production/WPiGammaHistos_ttbarlnu_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarToHadronic_2017.root histos/latest_production/WPiGammaHistos_ttbarToHadronic_2017.root
python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbarToSemiLeptonic_2017.root histos/latest_production/WPiGammaHistos_ttbarToSemiLeptonic_2017.root
# python generate_histos.py BDT 1 rootfiles/latest_production/MC/backgrounds/WPiGammaAnalysis_ttbar_2017.root histos/latest_production/WPiGammaHistos_ttbar_2017.root

python generate_histos.py BDT 1 rootfiles/latest_production/MC/signals/WPiGammaAnalysis_Signal_2017.root histos/latest_production/WPiGammaHistos_Signal_2017.root

python generate_histos.py BDT 1 rootfiles/latest_production/dataprocess/WPiGammaAnalysis_Data_2017.root histos/latest_production/WPiGammaHistos_Data_2017.root

#Merge samples
hadd histos/latest_production/WPiGammaHistos_QCD_2017.root histos/latest_production/WPiGammaHistos_QCDHT*_2017.root histos/latest_production/WPiGammaHistos_QCDDouble*_2017.root
#hadd histos/latest_production/WPiGammaHistos_QCDEM_2017.root histos/latest_production/WPiGammaHistos_QCDDouble*_2017.root
rm histos/latest_production/WPiGammaHistos_QCDHT*_2017.root
rm histos/latest_production/WPiGammaHistos_QCDDouble*_2017.root

hadd histos/latest_production/WPiGammaHistos_GammaJets_2017.root histos/latest_production/WPiGammaHistos_GammaJets*to*_2017.root
rm histos/latest_production/WPiGammaHistos_GammaJets*to*_2017.root

hadd histos/latest_production/WPiGammaHistos_STtW_2017.root histos/latest_production/WPiGammaHistos_Single*ToptW_2017.root
rm histos/latest_production/WPiGammaHistos_Single*ToptW_2017.root

hadd histos/latest_production/WPiGammaHistos_DY_2017.root histos/latest_production/WPiGammaHistos_DY*50_2017.root
rm histos/latest_production/WPiGammaHistos_DY*50_2017.root

hadd histos/latest_production/WPiGammaHistos_ttbar_2017.root histos/latest_production/WPiGammaHistos_ttbarTo*nic_2017.root
rm histos/latest_production/WPiGammaHistos_ttbarTo*nic_2017.root

hadd histos/latest_production/WPiGammaHistos_WJetsToLNu_2017.root histos/latest_production/WPiGammaHistos_WJetsToLNu*J_2017.root
rm histos/latest_production/WPiGammaHistos_WJetsToLNu*J_2017.root
